### ISSUE TITLE
Visualizer segfaults. 

### ISSUE THREAD

**Issue by s0217391** [iRath96/variance-aware-path-guiding#2]
Running on Ubuntu 18.04, using your code out of the box, the visualizer tool does not work: 

...
hooray
hooray
hooray
hooray
hooray
hooray
hooray
hooray
hooray
hooray
hooray
hooray
hooray
hooray
hooray
hooray
Loaded SD-Tree with 0 D-Trees.
fish: “./visualizer” terminated by signal SIGSEGV (Address boundary error)

**Comment by iRath96** [comment]
Hi, thank you for posting this issue. This typically only happens when you try to open an SD tree that contains no information -- for instance, when you open the SD tree generated during the final iteration (i.e. the one with the highest number following the scene name). Please let me know if this is the case here or if this affects an earlier SD tree.

**Comment by otherpj** [comment]
It affects all SD trees written out by your version of the code 

Sorry, I notice I posted this from a different account. I will try again on Monday to make 100% sure, but iirc, it happens on all trees.

**Comment by iRath96** [comment]
@otherpj I have just pushed a commit that should fix this issue. Please let me know if this helped.

**Comment by s0217391** [comment]
Yes, Fixed! thanks.
